// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NovaOrdem struct {
	ID    string  `json:"id"`
	Preco float64 `json:"preco"`
	Taxa  float64 `json:"taxa"`
}

type Query struct {
}
