// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: internal/infra/grpc/proto/protofiles/ordem.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrdemInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Taxa          float32                `protobuf:"fixed32,2,opt,name=taxa,proto3" json:"taxa,omitempty"`
	Preco         float32                `protobuf:"fixed32,3,opt,name=preco,proto3" json:"preco,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdemInput) Reset() {
	*x = OrdemInput{}
	mi := &file_internal_infra_grpc_proto_protofiles_ordem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdemInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdemInput) ProtoMessage() {}

func (x *OrdemInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_grpc_proto_protofiles_ordem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdemInput.ProtoReflect.Descriptor instead.
func (*OrdemInput) Descriptor() ([]byte, []int) {
	return file_internal_infra_grpc_proto_protofiles_ordem_proto_rawDescGZIP(), []int{0}
}

func (x *OrdemInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrdemInput) GetTaxa() float32 {
	if x != nil {
		return x.Taxa
	}
	return 0
}

func (x *OrdemInput) GetPreco() float32 {
	if x != nil {
		return x.Preco
	}
	return 0
}

type OrdemOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Taxa          float32                `protobuf:"fixed32,2,opt,name=taxa,proto3" json:"taxa,omitempty"`
	Preco         float32                `protobuf:"fixed32,3,opt,name=preco,proto3" json:"preco,omitempty"`
	Valor         float32                `protobuf:"fixed32,4,opt,name=valor,proto3" json:"valor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdemOutput) Reset() {
	*x = OrdemOutput{}
	mi := &file_internal_infra_grpc_proto_protofiles_ordem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdemOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdemOutput) ProtoMessage() {}

func (x *OrdemOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_grpc_proto_protofiles_ordem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdemOutput.ProtoReflect.Descriptor instead.
func (*OrdemOutput) Descriptor() ([]byte, []int) {
	return file_internal_infra_grpc_proto_protofiles_ordem_proto_rawDescGZIP(), []int{1}
}

func (x *OrdemOutput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrdemOutput) GetTaxa() float32 {
	if x != nil {
		return x.Taxa
	}
	return 0
}

func (x *OrdemOutput) GetPreco() float32 {
	if x != nil {
		return x.Preco
	}
	return 0
}

func (x *OrdemOutput) GetValor() float32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

type CriarOrdemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ordem         *OrdemInput            `protobuf:"bytes,1,opt,name=ordem,proto3" json:"ordem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CriarOrdemRequest) Reset() {
	*x = CriarOrdemRequest{}
	mi := &file_internal_infra_grpc_proto_protofiles_ordem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriarOrdemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriarOrdemRequest) ProtoMessage() {}

func (x *CriarOrdemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_grpc_proto_protofiles_ordem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriarOrdemRequest.ProtoReflect.Descriptor instead.
func (*CriarOrdemRequest) Descriptor() ([]byte, []int) {
	return file_internal_infra_grpc_proto_protofiles_ordem_proto_rawDescGZIP(), []int{2}
}

func (x *CriarOrdemRequest) GetOrdem() *OrdemInput {
	if x != nil {
		return x.Ordem
	}
	return nil
}

var File_internal_infra_grpc_proto_protofiles_ordem_proto protoreflect.FileDescriptor

const file_internal_infra_grpc_proto_protofiles_ordem_proto_rawDesc = "" +
	"\n" +
	"0internal/infra/grpc/proto/protofiles/ordem.proto\x12\x02pb\"F\n" +
	"\n" +
	"OrdemInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04taxa\x18\x02 \x01(\x02R\x04taxa\x12\x14\n" +
	"\x05preco\x18\x03 \x01(\x02R\x05preco\"]\n" +
	"\vOrdemOutput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04taxa\x18\x02 \x01(\x02R\x04taxa\x12\x14\n" +
	"\x05preco\x18\x03 \x01(\x02R\x05preco\x12\x14\n" +
	"\x05valor\x18\x04 \x01(\x02R\x05valor\"9\n" +
	"\x11CriarOrdemRequest\x12$\n" +
	"\x05ordem\x18\x01 \x01(\v2\x0e.pb.OrdemInputR\x05ordem2F\n" +
	"\fOrdemService\x126\n" +
	"\n" +
	"CriarOrdem\x12\x15.pb.CriarOrdemRequest\x1a\x0f.pb.OrdemOutput\"\x00B\x1eZ\x1cinternal/infra/grpc/proto/pbb\x06proto3"

var (
	file_internal_infra_grpc_proto_protofiles_ordem_proto_rawDescOnce sync.Once
	file_internal_infra_grpc_proto_protofiles_ordem_proto_rawDescData []byte
)

func file_internal_infra_grpc_proto_protofiles_ordem_proto_rawDescGZIP() []byte {
	file_internal_infra_grpc_proto_protofiles_ordem_proto_rawDescOnce.Do(func() {
		file_internal_infra_grpc_proto_protofiles_ordem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_infra_grpc_proto_protofiles_ordem_proto_rawDesc), len(file_internal_infra_grpc_proto_protofiles_ordem_proto_rawDesc)))
	})
	return file_internal_infra_grpc_proto_protofiles_ordem_proto_rawDescData
}

var file_internal_infra_grpc_proto_protofiles_ordem_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_infra_grpc_proto_protofiles_ordem_proto_goTypes = []any{
	(*OrdemInput)(nil),        // 0: pb.OrdemInput
	(*OrdemOutput)(nil),       // 1: pb.OrdemOutput
	(*CriarOrdemRequest)(nil), // 2: pb.CriarOrdemRequest
}
var file_internal_infra_grpc_proto_protofiles_ordem_proto_depIdxs = []int32{
	0, // 0: pb.CriarOrdemRequest.ordem:type_name -> pb.OrdemInput
	2, // 1: pb.OrdemService.CriarOrdem:input_type -> pb.CriarOrdemRequest
	1, // 2: pb.OrdemService.CriarOrdem:output_type -> pb.OrdemOutput
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_infra_grpc_proto_protofiles_ordem_proto_init() }
func file_internal_infra_grpc_proto_protofiles_ordem_proto_init() {
	if File_internal_infra_grpc_proto_protofiles_ordem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_infra_grpc_proto_protofiles_ordem_proto_rawDesc), len(file_internal_infra_grpc_proto_protofiles_ordem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_infra_grpc_proto_protofiles_ordem_proto_goTypes,
		DependencyIndexes: file_internal_infra_grpc_proto_protofiles_ordem_proto_depIdxs,
		MessageInfos:      file_internal_infra_grpc_proto_protofiles_ordem_proto_msgTypes,
	}.Build()
	File_internal_infra_grpc_proto_protofiles_ordem_proto = out.File
	file_internal_infra_grpc_proto_protofiles_ordem_proto_goTypes = nil
	file_internal_infra_grpc_proto_protofiles_ordem_proto_depIdxs = nil
}
