// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: internal/infra/grpc/proto/protofiles/ordem.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrdemService_CriarOrdem_FullMethodName = "/pb.OrdemService/CriarOrdem"
)

// OrdemServiceClient is the client API for OrdemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrdemServiceClient interface {
	CriarOrdem(ctx context.Context, in *CriarOrdemRequest, opts ...grpc.CallOption) (*OrdemOutput, error)
}

type ordemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrdemServiceClient(cc grpc.ClientConnInterface) OrdemServiceClient {
	return &ordemServiceClient{cc}
}

func (c *ordemServiceClient) CriarOrdem(ctx context.Context, in *CriarOrdemRequest, opts ...grpc.CallOption) (*OrdemOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrdemOutput)
	err := c.cc.Invoke(ctx, OrdemService_CriarOrdem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrdemServiceServer is the server API for OrdemService service.
// All implementations must embed UnimplementedOrdemServiceServer
// for forward compatibility.
type OrdemServiceServer interface {
	CriarOrdem(context.Context, *CriarOrdemRequest) (*OrdemOutput, error)
	mustEmbedUnimplementedOrdemServiceServer()
}

// UnimplementedOrdemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrdemServiceServer struct{}

func (UnimplementedOrdemServiceServer) CriarOrdem(context.Context, *CriarOrdemRequest) (*OrdemOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CriarOrdem not implemented")
}
func (UnimplementedOrdemServiceServer) mustEmbedUnimplementedOrdemServiceServer() {}
func (UnimplementedOrdemServiceServer) testEmbeddedByValue()                      {}

// UnsafeOrdemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrdemServiceServer will
// result in compilation errors.
type UnsafeOrdemServiceServer interface {
	mustEmbedUnimplementedOrdemServiceServer()
}

func RegisterOrdemServiceServer(s grpc.ServiceRegistrar, srv OrdemServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrdemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrdemService_ServiceDesc, srv)
}

func _OrdemService_CriarOrdem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CriarOrdemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdemServiceServer).CriarOrdem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrdemService_CriarOrdem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdemServiceServer).CriarOrdem(ctx, req.(*CriarOrdemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrdemService_ServiceDesc is the grpc.ServiceDesc for OrdemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrdemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OrdemService",
	HandlerType: (*OrdemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CriarOrdem",
			Handler:    _OrdemService_CriarOrdem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/infra/grpc/proto/protofiles/ordem.proto",
}
